### ISSUE TITLE
Merge QVMDevice / QPUDevice into same class

### ISSUE THREAD

**Issue by msohaibalam** [PennyLaneAI/pennylane-forest#28]
The `QVMDevice` and `QPUDevice` share many commonalities, and currently there exists code duplication between the two classes, which could be avoided. Furthermore, `QPUDevice` is currently a sub-class of `QVMDevice` anyway, and allows the user to generate a qpu-as-a-qvm lattice.

From a UX perspective, it would be better to merge the two classes into one, and simply allow the user to specify `device="Aspen-*" (`*=<qvm/qpu>`) to pick one or the other.

**Comment by mariaschuld** [comment]
Closing this issue for now, feel free to reopen.
