### ISSUE TITLE
PennyLane commit breaking the plugin

### ISSUE THREAD

**Issue by nvitucci** [PennyLaneAI/pennylane-forest#52]
I noticed that a [recent commit in PennyLane](https://github.com/XanaduAI/pennylane/commit/3abc013b37df685a2d3b6e3dfbffd8addfa8bbfe) introduced a bug in the master version of the plugin, resulting in a `KeyError: <Wires = [0]>` exception when the circuit is evaluated. Minimal example:

1. Install PennyLane with `pip`
2. Clone this repo and install it with `pip install -e .`
3. Run this code:

```python
import pennylane as qml

def circuit(angles, **kwargs):
    qml.RX(angles[0], wires=0)
    
dev = qml.device('forest.qvm', device='2q-qvm', shots=10, noisy=True)

params = [0.2]
qnode = qml.map(circuit, [qml.PauliZ(0)], dev)
print(qnode(params))
```

**Comment by josh146** [comment]
Thanks @nvitucci! We're in the process of adding a new wires class to PennyLane, and were attempting to add it in a non-breaking manner - looks like that hasn't worked :slightly_smiling_face: 

We'll have a think back over in PennyLane core and decide the best way to fix this

**Comment by antalszava** [comment]
Closing this after it has been resolved with updates such as https://github.com/PennyLaneAI/pennylane-forest/pull/55.
