### ISSUE TITLE
Gate object has no attribute 'params'

### ISSUE THREAD

**Issue by wjy99-c** [PennyLaneAI/pennylane-forest#61]
When I tried to run the example on [Plugin usage](https://pennylane-forest.readthedocs.io/en/latest/usage.html) and fixed the `KeyError: <Wires = [0]>` by editing the source code of pennylane-forest, I met another exception: `AttributeError: 'RZ' object has no attribute 'paras'` 

```
import pennylane as qml
from pennylane import expval, var


if __name__ == '__main__':


    dev_numpy = qml.device('forest.numpy_wavefunction', wires=2)
    dev_simulator = qml.device('forest.wavefunction', wires=2)
    dev_pyqvm = qml.device('forest.qvm', device='2q-pyqvm', shots=1000)
    dev_qvm = qml.device('forest.qvm', device='2q-qvm', shots=1000)


    @qml.qnode(dev_qvm)
    def circuit(x, y, z):
        qml.RZ(z, wires=[0])
        qml.RY(y, wires=[0])
        qml.RX(x, wires=[0])
        qml.CNOT(wires=[0, 1])
        print("hello")
        return expval(qml.PauliZ(0)), var(qml.PauliZ(1))

    print(circuit(0.2, 0.1, 0.3))
```
I edited the qvm.py and changed line 191 to `for param in operation.parameters:` and it fixed the exception.

**Comment by josh146** [comment]
Hi @wjy99-c! The `pip` installed version of the Rigetti plugin currently no longer works with the latest version of PennyLane.

Instead, you can install the GitHub version of the plugin:

```
pip uninstall pennylane-forest
pip install git+https://github.com/rigetti/pennylane-forest.git
```

**Comment by wjy99-c** [comment]
> Hi @wjy99-c! The `pip` installed version of the Rigetti plugin currently no longer works with the latest version of PennyLane.
> 
> Instead, you can install the GitHub version of the plugin:
> 
> ```
> pip uninstall pennylane-forest
> pip install git+https://github.com/rigetti/pennylane-forest.git
> ```

I c. Thanks!
